ai:
  max_tokens: 2048
  provider: gemini
  temperature: 0.7
app:
  debug: false
  name: Smart Book Publisher
  version: '2.0'
rewrite_strategies:
- dramatize
- summarize
- formalize
- expand
- simplify
scraper:
  default_url: https://en.wikisource.org/wiki/The_Gates_of_Morning/Book_1/Chapter_1
  screenshot_dir: screenshots
  timeout: 30
